export const almImages = [
	'/alumni/alm1.svg',
	'/alumni/alm2.svg',
	'/alumni/alm3.svg',
	'/alumni/alm4.svg',
	'/alumni/alm5.svg',
	'/alumni/alm6.svg',
	'/alumni/alm7.svg',
	'/alumni/alm8.svg',
	'/alumni/alm9.svg',
	'/alumni/alm10.svg',
	'/alumni/alm11.svg',
	'/alumni/alm12.svg',
	'/alumni/alm13.svg',
	'/alumni/alm14.svg',
	'/alumni/alm15.svg',
	'/alumni/alm16.svg',
	'/alumni/alm17.svg',
	'/alumni/alm18.svg',
  ];
  